dist: xenial
# используем язык java.
language: java
jdk:
- openjdk8
# используем режим обычного пользователя для сборки проекта.
sudo: true

services:
- postgresql
addons:
  postgresql: "10"
  apt:
    packages:
    - postgresql-10
    - postgresql-client-10
    - openjfx

before_script:
# Use default port
- sudo sed -i 's/port = 5433/port = 5432/' /etc/postgresql/10/main/postgresql.conf
# Use 9.6 auth config:
- sudo cp /etc/postgresql/{9.6,10}/main/pg_hba.conf
- sudo service postgresql restart

# после выполнения сборки запустить скрипт, который будет собирать статистику по JaCoCo
# Здесь используется сторонни сервис https://codecov.io/
after_success:
- bash <(curl -s https://codecov.io/bash)


# Отправлять уведомление на почту youremail@smtp.ru если сборка упала
notifications:
  email:
    recipients:
    - bassbass@yandex.ru
    on_success: never # default: change
    on_failure: always # default: always
